INSERT IGNORE INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Uncategorized', 'uncategorized', 0),
(2, 'Business', 'business', 0),
(3, 'Charming', 'charming', 0),
(4, 'Classic', 'classic', 0),
(5, 'Green', 'green', 0),
(6, 'Luxury', 'luxury', 0),
(7, 'Quaint', 'quaint', 0),
(8, 'Quite', 'quite', 0),
(9, 'Romantic', 'romantic', 0),
(10, 'Standard', 'standard', 0),
(11, 'Mid-range', 'mid-range', 0),
(12, 'Party', 'party', 0),
(13, 'Best value', 'best-value', 0),
(14, 'Boutique', 'boutique', 0),
(15, 'Budget', 'budget', 0),
(16, 'Trendy', 'trendy', 0),
(17, 'Cultural events', 'cultural-events', 0),
(18, 'Tiptoe', 'tiptoe', 0),
(19, 'Tulips', 'tulips', 0),
(20, 'Washington', 'washington', 0),
(21, 'Carnivals', 'carnivals', 0),
(22, 'Gallery', 'post-format-gallery', 0),
(23, 'Mountains', 'mountains', 0),
(24, 'National', 'national', 0),
(25, 'Parks', 'parks', 0),
(26, 'beaches', 'beaches', 0),
(27, 'Beauty', 'beauty', 0),
(28, 'Cultural', 'cultural', 0),
(29, 'Museums', 'museums', 0),
(30, 'National parks', 'national-parks', 0),
(31, 'Beauty beaches', 'beauty-beaches', 0),
(32, 'Mountains', 'mountains', 0),
(33, 'Museums', 'museums', 0),
(34, 'Image', 'post-format-image', 0),
(35, 'Parks and Carnivals', 'parks-and-carnivals', 0),
(36, 'Air Conditioning', 'air-conditioning', 0),
(37, 'Flat Screen TV', 'flat-screen-tv', 0),
(38, 'Hair dryer', 'bathtub', 0),
(39, 'Hot water', 'terrace', 0),
(40, 'Kitchen', 'patio', 0),
(41, 'Queen Room', 'queen-room', 0),
(42, 'Shampoo', 'soundproof', 0),
(43, 'Wifi', 'mini-bar', 0),
(44, 'Deluxe', 'deluxe', 0),
(45, 'Normal', 'normal', 0),
(46, 'Standard Double-Double Room', 'standard-double-double-room', 0),
(47, 'Standard Room', 'standard-room', 0),
(48, 'Family Suite', 'family-suite', 0),
(49, 'Footer New', 'footer-new', 0),
(50, 'Footer New 2', 'footer-new-2', 0),
(51, 'Hotel Menu', 'hotel-menu', 0),
(52, 'Air Conditioning', 'air-conditioning', 0),
(53, 'Airport Transport', 'airport-transport', 0),
(54, 'Fitness Center', 'fitness-center', 0),
(55, 'Flat Tv', 'flat-tv', 0),
(56, 'Heater', 'heater', 0),
(57, 'Internet – Wifi', 'internet-wifi', 0),
(58, 'Parking', 'parking', 0),
(59, 'Pool', 'pool', 0),
(60, 'Restaurant', 'restaurant', 0),
(61, 'Smoking Room', 'smoking-room', 0),
(62, 'Spa &amp; Sauna', 'spa-sauna', 0),
(63, 'Washer &amp; Dryer', 'washer-dryer', 0),
(64, 'simple', 'simple', 0),
(65, 'grouped', 'grouped', 0),
(66, 'variable', 'variable', 0),
(67, 'external', 'external', 0),
(68, 'exclude-from-search', 'exclude-from-search', 0),
(69, 'exclude-from-catalog', 'exclude-from-catalog', 0),
(70, 'featured', 'featured', 0),
(71, 'outofstock', 'outofstock', 0),
(72, 'rated-1', 'rated-1', 0),
(73, 'rated-2', 'rated-2', 0),
(74, 'rated-3', 'rated-3', 0),
(75, 'rated-4', 'rated-4', 0),
(76, 'rated-5', 'rated-5', 0),
(77, 'Uncategorized', 'uncategorized', 0),
(78, 'City trips', 'city-trips', 0),
(79, 'Ecotourism', 'ecotourism', 0),
(80, 'Escorted Tour', 'escorted-tour', 0),
(81, 'Group Tour', 'group-tour', 0),
(82, 'Hosted tours', 'hosted-tours', 0),
(83, 'Ligula', 'ligula', 0),
(84, '0 – 3 hours', '0-3-hours', 0),
(85, '3- 5 hours', '3-5-hours', 0),
(86, '5 – 7 hours', '5-7-hours', 0),
(87, 'Full day (7+ hours)', 'full-day-7-hours', 0),
(88, 'Multi day', 'multi-day', 0),
(89, 'English', 'english', 0),
(90, 'Espanol', 'espanol', 0),
(91, 'Francais', 'francais', 0),
(92, 'Japanese', 'japanese', 0),
(93, 'Vietnamese', 'vietnamese', 0),
(94, 'Mega 1', 'mega-1', 0),
(95, 'Mega 2', 'mega-2', 0),
(96, 'Mega 3', 'mega-3', 0),
(97, 'page', 'page', 0),
(98, 'traveler', 'traveler', 0);